# NOTE: Generated By HttpRunner v3.1.4
# FROM: api/demo_api.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemoApi(HttpRunner):

    config = Config("demo api")

    teststeps = [
        Step(
            RunRequest("demo api")
            .with_variables(**{"var1": "login", "var2": "test"})
            .post("/api/uavcontrol/user/$var1")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"key": "$var2"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoApi().test_start()
